/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculo;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JOptionPane;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author DELL
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_derivadas1 = new javax.swing.JButton();
        btn_funciones = new javax.swing.JButton();
        btn_matrizes = new javax.swing.JButton();
        btn_derivadas = new javax.swing.JButton();
        btn_limites = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));

        btn_derivadas1.setBackground(new java.awt.Color(81, 156, 254));
        btn_derivadas1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_derivadas1.setForeground(new java.awt.Color(255, 255, 255));
        btn_derivadas1.setText("Aplicaciones");
        btn_derivadas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_derivadas1.setBorderPainted(false);
        btn_derivadas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_derivadas1ActionPerformed(evt);
            }
        });

        btn_funciones.setBackground(new java.awt.Color(81, 156, 254));
        btn_funciones.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_funciones.setForeground(new java.awt.Color(255, 255, 255));
        btn_funciones.setText("Funciones");
        btn_funciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_funciones.setBorderPainted(false);
        btn_funciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_funcionesActionPerformed(evt);
            }
        });

        btn_matrizes.setBackground(new java.awt.Color(81, 156, 254));
        btn_matrizes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_matrizes.setForeground(new java.awt.Color(255, 255, 255));
        btn_matrizes.setText("Matrices");
        btn_matrizes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_matrizes.setBorderPainted(false);
        btn_matrizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matrizesActionPerformed(evt);
            }
        });

        btn_derivadas.setBackground(new java.awt.Color(81, 156, 254));
        btn_derivadas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_derivadas.setForeground(new java.awt.Color(255, 255, 255));
        btn_derivadas.setText("Derivadas");
        btn_derivadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_derivadas.setBorderPainted(false);
        btn_derivadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_derivadasActionPerformed(evt);
            }
        });

        btn_limites.setBackground(new java.awt.Color(81, 156, 254));
        btn_limites.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_limites.setForeground(new java.awt.Color(255, 255, 255));
        btn_limites.setText("Limites");
        btn_limites.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_limites.setBorderPainted(false);
        btn_limites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limitesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_matrizes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btn_funciones, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btn_limites, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btn_derivadas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btn_derivadas1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_derivadas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limites, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_derivadas1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_matrizes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_funciones, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_funcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_funcionesActionPerformed
        
        //String expresion=JOptionPane.showInputDialog("Inserta la funcion a graficar ");
        
        new Funciones(new javax.swing.JFrame(),true).setVisible(true);
        
    }//GEN-LAST:event_btn_funcionesActionPerformed

    private void btn_matrizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matrizesActionPerformed
        // TODO add your handling code here:
        new Matrices(new javax.swing.JFrame(),true).setVisible(true);
    }//GEN-LAST:event_btn_matrizesActionPerformed

    private void btn_derivadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_derivadasActionPerformed
        // TODO add your handling code here:
        new Derivadas(new javax.swing.JFrame(),true).setVisible(true);
    }//GEN-LAST:event_btn_derivadasActionPerformed

    private void btn_limitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limitesActionPerformed
        // TODO add your handling code here:
        new Limites(new javax.swing.JFrame(),true).setVisible(true);//hacemo visible la ventana
    }//GEN-LAST:event_btn_limitesActionPerformed

    private void btn_derivadas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_derivadas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_derivadas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_derivadas;
    private javax.swing.JButton btn_derivadas1;
    private javax.swing.JButton btn_funciones;
    private javax.swing.JButton btn_limites;
    private javax.swing.JButton btn_matrizes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
